---
- name: Update hosts file
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ ansible_hostname }}"
              insertafter="^127\.0\.0\.1 localhost.*$"
  become: yes

- name: Create the directory for the BookKeeper config files
  file:
    path: "{{ bookkeeper_config_dir }}"
    state: directory
    mode: 0755
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    recurse: yes
  become: yes

- name: Move the bk_server file to the host
  template:
    src: templates/bk_server.conf.j2
    dest: "{{ bookkeeper_config_dir }}/bk_server.conf"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Move the bkenv file to the host
  template:
    src: templates/bkenv.sh
    dest: "{{ bookkeeper_config_dir }}/bkenv.sh"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Move the log4j properties file to the host
  template:
    src: templates/log4j.properties
    dest: "{{ bookkeeper_config_dir }}/log4j.properties"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Move the log4j shell file to the host
  template:
    src: templates/log4j.shell.properties
    dest: "{{ bookkeeper_config_dir }}/log4j.shell.properties"
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"
    mode: 0555

- name: Run the BookKeeper container
  docker:
    name: "{{ bookkeeper_container_name }}"
    image: "{{ bookkeeper_docker_image }}"
    detach: yes
    state: reloaded
    restart_policy: always
    restart_policy_retry: 128
    volumes:
      - "{{ bookkeeper_config_dir }}:/bookkeeper-server-4.3.2/conf"
    ports:
      - "{{ bookie_host_port }}:{{ bookie_container_port }}"
    expose:
      - "{{ bookie_container_port }}"

- name: Wait for Bookie server to come up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: "{{ bookie_host_port }}"
    delay: 0
    timeout: 60
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
